<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TSAppConfigPatcherTask" Version="2.1.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RebarComponentInserter\RebarComponentInserter.csproj" />
	</ItemGroup>

</Project>
